import sys
import os
from typing import Annotated, TypedDict, List, Sequence, Optional
from dotenv import load_dotenv
from langchain_core.messages import BaseMessage, HumanMessage , AIMessage
from langgraph.graph import END, StateGraph , message
from operator import add
from chains import generation_chain, reflection_chain, summarize_chain, research_chain
from langchain_ollama import OllamaLLM
from langchain_community.document_loaders import PyPDFLoader
from pydantic import BaseModel, Field

load_dotenv() 

REFLECT = "reflect"
GENERATE = "generate"
RESEARCH = "research"
SUMMARIZE = "summarize"


def get_pdf_content(file_path: str) -> str:
    loader = PyPDFLoader(file_path)
    documents = loader.load()
    # combine all pages into one string
    content = "\n".join([doc.page_content for doc in documents])
    return content



# AIMessage: Responses generated by the model, 
# including text content, tool calls, and metadata
# response = model.invoke("Explain AI")
# print(type(response))  # <class 'langchain.messages.AIMessage'>


class GraphState(BaseModel):
    job_description: str
    summarize : Optional[str]  = None
    research_brief: Optional[str] = None
    current_draft : Optional[str] = None #expect a str
    critique: Optional[str] = None
    iterations: int = 0
    optimization_score: int = Field(default= 0, ge=0 , le=100)
    
    # memory (The message Thread): This is a list of all the messages that have been exchanged in the conversation so far.
    chat_history: Annotated[list[BaseMessage], add] = Field(default_factory=list)
    


def summarize_node(state: GraphState):
    
    summarize_input = HumanMessage(
        content=(
             "Research Brief:\n"
             f"{state.research_brief}\n\n"
             "Current Draft:\n"
             f"{state.current_draft}\n\n"
        ))
    
    
    summary = summarize_chain.invoke({
        "messages": [summarize_input]
    })
    
    return {
        
            "summarize": summary,
    }




def research_node(state: GraphState):
    research_input = HumanMessage(
        
        content=(
            "Job Description:\n"
            f"{state.job_description}\n\n"
            "Resume:\n"
            f"{state.current_draft}\n\n"
            
        )
        
    )
    
    research_brief = research_chain.invoke({
        "messages": [research_input]
    })
    
    return {
        
        "research_brief": research_brief
            
    }


#The Logic: A Node is just a Python function that takes the current state, 
# does some work (calls Llama 3), and returns the update.
def generate_node(state: GraphState) -> dict: # every node receives the entire state
    parts = []
    if state.summarize:
        parts.append(f"Summarize: {state.summarize}")
    if state.critique:
        parts.append(f"Critique: {state.critique}")
    if not parts:
        parts.append(f"Create the First Draft: [from this resume , {state.current_draft}, based on the Job Description: {state.job_description}]")
    
    generate_input = HumanMessage(
        content=("\n\n".join(parts)))
    
    rew_resume = generation_chain.invoke({ 
                                          
                                          "messages": [generate_input]
                                      
                                        })  # the messages varible comes from MessagesPlaceholder(variable_name="messages")
    # LangGraph will 'add' this one message to your 'chat_history'
    return {
        "current_draft": rew_resume,
        "iterations": state.iterations + 1,
        }  # we return the entire chat history with the new message appended at the end. This is important for reflection to work properly, as it needs the full context of the conversation to provide meaningful feedback.

def reflect_node(state: GraphState) -> dict:
    # 1. Pass the FULL chat_history so the Recruiter sees the JD AND the Draft
    
    reflect_input = HumanMessage(
        content=(
            "Job Description:\n"
            f"{state.job_description}\n\n"
            "Current Draft:\n"
            f"{state.current_draft}\n\n"
        )
    )
    
    critique = reflection_chain.invoke({
        
        "messages": [reflect_input]  #Dot notataion for pydantic
    })
    
    # 2. Return the critique as an AIMessage (since the Recruiter is an AI)
    # Note: Some people prefer wrapping critiques in HumanMessage 
    # to "trick" the next node into thinking a human gave feedback, 
    # but AIMessage is technically more accurate here.
    return {
        
        "critique": critique
            
            }

graph = StateGraph(GraphState)    


def should_continue(state: GraphState) -> str:
    # This function checks the current state to decide whether we should continue reflecting and generating or if we should stop and return the final resume.
    Max_iterations = 3
    
    if state.iterations >= Max_iterations:
        return END  # Stop if we've reached the maximum number of iterations
    else:
        return "continue" # Otherwise, we continue reflecting and generating until we hit the stopping condition
    



if __name__ == "__main__":
    file_name = sys.argv[1]
    print("PASTE THE JOB DESCRIPTION BELOW (Press Enter + Ctrl+Z on Windows or Ctrl+D on Mac when finished):")
    jd= sys.stdin.read()
    path= os.path.join("D:\\New Projects\\LLM\\Langgraph\\Basic_reflection_system", file_name)
    resume_content = get_pdf_content(path)
    
    #add nodes
    graph.add_node(GENERATE, generate_node)
    graph.add_node(REFLECT, reflect_node)
    graph.add_node(RESEARCH, research_node)
    graph.add_node(SUMMARIZE, summarize_node)
    
    #set entry point
    graph.set_entry_point(RESEARCH)
    graph.add_edge(RESEARCH, SUMMARIZE)
    graph.add_edge(SUMMARIZE, GENERATE)
    
    
    graph.add_conditional_edges(
        "generate", should_continue,
        {
            "continue": "reflect",  # If we should continue, go to the REFLECT node
            END: END  # If we should stop, go to the END state
        }
        
        
    )
    
    graph.add_edge(REFLECT, GENERATE)  # Add a self-loop on the REFLECT node to allow for multiple rounds of reflection
   
    app = graph.compile()
    print(app.get_graph().draw_mermaid())
    app.get_graph().print_ascii()
    
    # EXECUTE
    
    initial_inputs = {
        
    "job_description": jd,
    "current_draft": resume_content,
    "iterations": 0
}
    
    print("\n--- Processing your Resume (Llama 3 is thinking...) ---")
    final_state = app.invoke(initial_inputs)
    print(final_state["current_draft"])