import sys
import os
from typing import Annotated, TypedDict, List, Sequence
from dotenv import load_dotenv
from langchain_core.messages import BaseMessage, HumanMessage , AIMessage
from langgraph.graph import END, StateGraph , message
from operator import add
from chains import generation_chain, reflection_chain
from langchain_ollama import OllamaLLM
from langchain_community.document_loaders import PyPDFLoader


load_dotenv() 

REFLECT = "reflect"
GENERATE = "generate"


def get_pdf_content(file_path: str) -> str:
    loader = PyPDFLoader(file_path)
    documents = loader.load()
    # combine all pages into one string
    content = "\n".join([doc.page_content for doc in documents])
    return content



# AIMessage: Responses generated by the model, 
# including text content, tool calls, and metadata
# response = model.invoke("Explain AI")
# print(type(response))  # <class 'langchain.messages.AIMessage'>


class GraphState(TypedDict):
    # This 'add' tells LangGraph to append new messages to the list
    chat_history: Annotated[list[BaseMessage], add]





#The Logic: A Node is just a Python function that takes the current state, 
# does some work (calls Llama 3), and returns the update.
def generate_node(State: GraphState) -> dict: # every node recives the entire state
    
    result = generation_chain.invoke({ "messages": State["chat_history"] })  # the messages varible comes from MessagesPlaceholder(variable_name="messages")
    # LangGraph will 'add' this one message to your 'chat_history'
    return {"chat_history": [AIMessage(content = result)]}  # we return the entire chat history with the new message appended at the end. This is important for reflection to work properly, as it needs the full context of the conversation to provide meaningful feedback.

def reflect_node(State: GraphState) -> dict:
    # 1. Pass the FULL chat_history so the Recruiter sees the JD AND the Draft
    result = reflection_chain.invoke({
        "messages": State["chat_history"] 
    })
    
    # 2. Return the critique as an AIMessage (since the Recruiter is an AI)
    # Note: Some people prefer wrapping critiques in HumanMessage 
    # to "trick" the next node into thinking a human gave feedback, 
    # but AIMessage is technically more accurate here.
    return {"chat_history": [AIMessage(content=result)]}

graph = StateGraph(GraphState)    

graph.add_node(GENERATE, generate_node)
graph.add_node(REFLECT, reflect_node)


def should_continue(state: GraphState) -> str:
    # This is a simple stopping condition that checks if the last message contains "Final CV"
    # In a real application, you might want to use a more sophisticated method, 
    # such as checking for user input or a specific signal in the messages.
    if len(state["chat_history"]) > 4:
        return END  
    
    return REFLECT  # Otherwise, we continue reflecting and generating until we hit the stopping condition




if __name__ == "__main__":
    file_name = sys.argv[1]
    print("PASTE THE JOB DESCRIPTION BELOW (Press Enter + Ctrl+Z on Windows or Ctrl+D on Mac when finished):")
    jd= sys.stdin.read()
    path= os.path.join("D:\\New Projects\\LLM\\Langgraph\\Basic_reflection_system", file_name)
    resume_content = get_pdf_content(path)
    
    graph.set_entry_point(GENERATE)
    graph.add_conditional_edges(GENERATE, should_continue)  # Add a conditional edge to check if we should stop after reflection
    graph.add_edge(REFLECT, GENERATE)  # Always generate after reflection 
    app = graph.compile()
    print(app.get_graph().draw_mermaid())
    app.get_graph().print_ascii()
    
    # EXECUTE
    
    inputs = {
    "chat_history": [
        HumanMessage(content=f"JD: {jd[:1000]}\n\nResume: {resume_content[:2000]}")
    ]
}
    
    print("\n--- Processing your Resume (Llama 3 is thinking...) ---")
    final_state = app.invoke(inputs)
    print(final_state["chat_history"][-1].content)